import { Property } from "@/types";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "farmhouse-chhatarpur-1",
    title: "The Oberoi Green Acre Estate",
    slug: "oberoi-green-acre-estate-chhatarpur",
    description: "Expansive 4.5 Acre gated farmhouse sanctuary nestled in the ultra-prime Chhatarpur green belt. Features private mango orchards, Olympic-sized swimming pool, 6-suite luxury residence, and 24/7 high-security perimeter.",
    property_type: "Farmhouse",
    price: 320000000,
    land_area_value: 4.5,
    land_area_unit: "acre",
    land_area_sqft_normalized: 196020,
    built_up_area_sqft: 14500,
    bedrooms: 6,
    bathrooms: 8,
    furnishing: "Fully Furnished",
    status: "AVAILABLE",
    verification_status: "VERIFIED",
    is_featured: true,
    owner_id: "seller-1",
    location_id: "loc-1",
    location: {
      id: "loc-1",
      state: "Delhi",
      city: "Delhi",
      locality: "Chhatarpur Farms",
      address: "Lane 4, DLF Chhatarpur Farms",
    },
    media: [
      { id: "m1", property_id: "farmhouse-chhatarpur-1", media_type: "IMAGE", url: "/images/farmhouse-hero.jpg", is_primary: true, display_order: 0 },
      { id: "m2", property_id: "farmhouse-chhatarpur-1", media_type: "IMAGE", url: "/images/bedroom.jpg", is_primary: false, display_order: 1 }
    ],
    amenities: [
      { id: "a1", name: "Private Swimming Pool" },
      { id: "a2", name: "Landscaped Orchards" },
      { id: "a3", name: "Guard House & CCTV" }
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "farmhouse-dlf-gurgaon-2",
    title: "The Magnolia Meadow Farmhouse",
    slug: "magnolia-meadow-farmhouse-gurgaon",
    description: "Exclusive 3 Acre landscaped farmhouse situated off Golf Course Extension road with world-class landscaping, gazebo, organic vegetable patch, and bespoke entertainment deck.",
    property_type: "Farmhouse",
    price: 240000000,
    land_area_value: 3,
    land_area_unit: "acre",
    land_area_sqft_normalized: 130680,
    built_up_area_sqft: 11000,
    bedrooms: 5,
    bathrooms: 6,
    furnishing: "Fully Furnished",
    status: "AVAILABLE",
    verification_status: "VERIFIED",
    is_featured: true,
    owner_id: "seller-2",
    location_id: "loc-2",
    location: {
      id: "loc-2",
      state: "Haryana",
      city: "Gurgaon",
      locality: "DLF Farms",
      address: "Sohna Road Greens, Gurgaon",
    },
    media: [
      { id: "m3", property_id: "farmhouse-dlf-gurgaon-2", media_type: "IMAGE", url: "/images/estate.jpg", is_primary: true, display_order: 0 },
      { id: "m4", property_id: "farmhouse-dlf-gurgaon-2", media_type: "IMAGE", url: "/images/bedroom.jpg", is_primary: false, display_order: 1 }
    ],
    amenities: [
      { id: "a4", name: "Tennis Court" },
      { id: "a5", name: "Organic Farm Patch" },
      { id: "a6", name: "100% Solar Powered" }
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "bungalow-gurgaon-3",
    title: "The Horizon Grand Bungalow",
    slug: "horizon-grand-bungalow-gurgaon",
    description: "Ultra-contemporary 8,500 sqft designer architectural bungalow with floor-to-ceiling glass facades, private temperature-controlled pool, and Italian marble finishes.",
    property_type: "Luxury Bungalow",
    price: 185000000,
    land_area_value: 1200,
    land_area_unit: "sqyd",
    land_area_sqft_normalized: 10800,
    built_up_area_sqft: 8500,
    bedrooms: 5,
    bathrooms: 6,
    furnishing: "Fully Furnished",
    status: "AVAILABLE",
    verification_status: "VERIFIED",
    is_featured: true,
    owner_id: "seller-3",
    location_id: "loc-3",
    location: {
      id: "loc-3",
      state: "Haryana",
      city: "Gurgaon",
      locality: "Golf Course Road",
      address: "Sector 42, Golf Course Road",
    },
    media: [
      { id: "m5", property_id: "bungalow-gurgaon-3", media_type: "IMAGE", url: "/images/bungalow.jpg", is_primary: true, display_order: 0 },
      { id: "m6", property_id: "bungalow-gurgaon-3", media_type: "IMAGE", url: "/images/bedroom.jpg", is_primary: false, display_order: 1 }
    ],
    amenities: [
      { id: "a7", name: "Smart Home Automation" },
      { id: "a8", name: "Private Elevator" },
      { id: "a9", name: "Rooftop Lounge" }
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "villa-alibaug-4",
    title: "The Casuarina Coastal Villa",
    slug: "casuarina-coastal-villa-alibaug",
    description: "Secluded 2.2 Acre beachfront sanctuary in Mandwa, Alibaug. Surrounded by tall coconut groves with direct shoreline access and an infinity pool facing the Arabian Sea.",
    property_type: "Villa",
    price: 165000000,
    land_area_value: 2.2,
    land_area_unit: "acre",
    land_area_sqft_normalized: 95832,
    built_up_area_sqft: 7500,
    bedrooms: 4,
    bathrooms: 5,
    furnishing: "Fully Furnished",
    status: "AVAILABLE",
    verification_status: "VERIFIED",
    is_featured: true,
    owner_id: "seller-4",
    location_id: "loc-4",
    location: {
      id: "loc-4",
      state: "Maharashtra",
      city: "Alibaug",
      locality: "Mandwa Beach Belt",
      address: "Awas - Mandwa Road",
    },
    media: [
      { id: "m7", property_id: "villa-alibaug-4", media_type: "IMAGE", url: "/images/villa.jpg", is_primary: true, display_order: 0 },
      { id: "m8", property_id: "villa-alibaug-4", media_type: "IMAGE", url: "/images/bedroom.jpg", is_primary: false, display_order: 1 }
    ],
    amenities: [
      { id: "a10", name: "Direct Beach Access" },
      { id: "a11", name: "Private Jetty Access" },
      { id: "a12", name: "Infinity Lap Pool" }
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "villa-goa-5",
    title: "The Heritage Palm Manor",
    slug: "heritage-palm-manor-assagao-goa",
    description: "Restored Portuguese-Goan luxury villa in coveted Assagao. Features grand high-beam wooden ceilings, private courtyard pool, and serene tropical landscaping.",
    property_type: "Villa",
    price: 145000000,
    land_area_value: 1800,
    land_area_unit: "sqyd",
    land_area_sqft_normalized: 16200,
    built_up_area_sqft: 6800,
    bedrooms: 4,
    bathrooms: 5,
    furnishing: "Fully Furnished",
    status: "AVAILABLE",
    verification_status: "VERIFIED",
    is_featured: true,
    owner_id: "seller-5",
    location_id: "loc-5",
    location: {
      id: "loc-5",
      state: "Goa",
      city: "Goa",
      locality: "Assagao & Vagator",
      address: "Badem Junction, Assagao",
    },
    media: [
      { id: "m9", property_id: "villa-goa-5", media_type: "IMAGE", url: "/images/hills.jpg", is_primary: true, display_order: 0 },
      { id: "m10", property_id: "villa-goa-5", media_type: "IMAGE", url: "/images/bedroom.jpg", is_primary: false, display_order: 1 }
    ],
    amenities: [
      { id: "a13", name: "Heritage Architecture" },
      { id: "a14", name: "Courtyard Pool" },
      { id: "a15", name: "Chef's Kitchen" }
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "farmhouse-lonavala-6",
    title: "The Cloud Crest Hilltop Farm",
    slug: "cloud-crest-hilltop-farm-lonavala",
    description: "Panoramic 5 Acre hilltop farmhouse estate in Tungarli Hills, Lonavala. Boasts misty mountain views, private tea-coffee grove, and outdoor infinity jacuzzi deck.",
    property_type: "Farmhouse",
    price: 195000000,
    land_area_value: 5,
    land_area_unit: "acre",
    land_area_sqft_normalized: 217800,
    built_up_area_sqft: 9200,
    bedrooms: 5,
    bathrooms: 6,
    furnishing: "Fully Furnished",
    status: "AVAILABLE",
    verification_status: "VERIFIED",
    is_featured: true,
    owner_id: "seller-6",
    location_id: "loc-6",
    location: {
      id: "loc-6",
      state: "Maharashtra",
      city: "Lonavala",
      locality: "Tungarli Hills",
      address: "Old Khandala Road",
    },
    media: [
      { id: "m11", property_id: "farmhouse-lonavala-6", media_type: "IMAGE", url: "/images/farmhouse-hero.jpg", is_primary: true, display_order: 0 },
      { id: "m12", property_id: "farmhouse-lonavala-6", media_type: "IMAGE", url: "/images/estate.jpg", is_primary: false, display_order: 1 }
    ],
    amenities: [
      { id: "a16", name: "360° Mountain Views" },
      { id: "a17", name: "Private Helipad" },
      { id: "a18", name: "Heated Jacuzzi" }
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];
